### ISSUE TITLE
Integrate into Haystack Home

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-integrations#2]
We need to integrate the `.md` files in the `/integrations` directory here into Haystack Home. The idea is that it would work similar to the tutorials repo -> When an `.md` is merged onto this repo, it's pushed to haystack-home too. 
The `.md` files (for now) have the following frontmatter:

```
---
name: Azure Translate Node
description: TranslateAnswer and TranslateQuery Nodes that use the Azure Translate endpoint
authors:
    - name: recrudesce (Russ)
      socials:
        github: recrudesce
        twitter: recrudesce
pypi:
repo: https://github.com/recrudesce/haystack_translate_node
type: Custom Node
report_issue: https://github.com/recrudesce/haystack_translate_node/issues
---
```
To be discplayed on the cards on https://haystack.deepsret.ai/integrations:
- name
- description
- 'Type' as a tag (like we have the level tags on Tutorials)

To be used as filters:
- type

When opened, display page or modal (like the prompthub modal):
- Render the authors and their socials
- Render some sort of buttons below the Title (name),  description and authors the options such as "PyPI package" and "GitHub repo"
- Render a 'report and issue' button separatelly (to the right?) that forwards to the url mentioned in the frontmatter.
- Render the content in similar style to the tutorial content

We can copy this layout: 

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/15802862/229488546-b9f85345-5189-4921-8f5d-33b24f793903.png">

The only change I woule like to have is to have the card colors inverted to what we have here (dark purple background with white text)

Next steps will be:
- We want to have 'upvote and downvote' functionality
- We would like to have search capability.
